config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/about' => 'static_pages#about'
  get '/media' => 'static_pages#media'
  get '/auditions' => 'static_pages#auditions'
  get 'fetch_media' => 'static_pages#from_path', as: 'fetch_media'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end

	def about
	end

	def media
		@media_path = 'xHmjKRIrbkA'
		@autoplay = 1
	end

	def bookings

	end

	def auditions
	end

	def from_path
		@media_path = params[:youtube_id]
		@autoplay = 1
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def embed(youtube_url)
		youtube_id = youtube_url.split("=").last
		content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!-- ============================================================= SECTION – SHARE ============================================================= -->
	
<section id="share" class="dark-bg">
	<div class="row">
		
		<div class="col-sm-6 reset-padding-right">
			<a href="https://www.facebook.com/duketazns" class="btn-share-md" target="_blank">
				<i class="icon-s-facebook"></i>
				<i class="ion-social-facebook"></i>
			</a>
		</div><!-- /.col -->
	
		
		<div class="col-sm-6 reset-padding-left">
			<a href="https://www.youtube.com/channel/UCc8zO5JFsL8R_JhCejQCEzg" target="_blank" class="btn-share-md">
				<i class="icon-s-gplus"></i>
				<i class="ion-social-youtube"></i>
			</a>
		</div><!-- /.col -->
		
	</div><!-- /.row -->
</section>

<!-- ============================================================= SECTION – SHARE : END ============================================================= -->

<!-- ============================================================= FOOTER ============================================================= -->
		
<footer class="light-bg">
	<div class="container inner">
		<div class="row">
			
			<div class="col-md-6 col-sm-6 inner">
				<h4>Who we are</h4>
				<a href="/"><%= image_tag("logo.png", class: "logo img-intext") %>
				<p>Founded in 2001, The Temptasians are Duke University’s co-ed Asian a cappella group, comprised of talented Asian singers who love to sing.</p>
				<a href="/about" class="txt-btn">More about us</a>
			</div><!-- /.col -->
			
			
			<div class="col-md-6 col-sm-6 inner">
				<h4>Get In Touch</h4>
				<p>We are available for bookings!</p>
				<ul class="contacts">
					<li><i class="ion-location contact"></i>Duke University, Durham, NC 27708</li>
					<li><a href="mailto:duketemptasians@gmail.com" ><i class="ion-email contact"></i> duketemptasians@gmail.com</a></li>
				</ul><!-- /.contacts -->
			</div><!-- /.col -->
			
		</div><!-- /.row --> 
	</div><!-- .container -->
  
	<div class="footer-bottom">
		<div class="container inner">
			<p class="pull-left">Created by U-jo</p>
			<ul class="footer-menu pull-right">
				<li><a href="/">Home</a></li>
				<li><a href="/about">About us</a></li>
				<li><a href="/media">Media</a></li>
				<li><%= link_to "Bookings" , {:action => "index", :controller => "static_pages", :anchor => "bookings" } %></li>
				<li><a href="/auditions">Auditions</a></li>
			</ul><!-- .footer-menu -->
		</div><!-- .container -->
	</div><!-- .footer-bottom -->
</footer>

<!-- ============================================================= FOOTER : END ============================================================= -->

app/views/layouts/_navigation.html.erb
<div class="navbar">
	<div class="navbar-header">
		<div class="container">
			
			<!-- ============================================================= LOGO MOBILE ============================================================= -->
			
			<%= link_to root_url, class: "navbar-brand" do %>
				<%= image_tag("logo.png", class: "logo") %>
			<% end %>
			
			<!-- ============================================================= LOGO MOBILE : END ============================================================= -->
			
			<a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='ion-navicon-round'></i></a>
			
		</div><!-- /.container -->
	</div><!-- /.navbar-header -->
	<div class="yamm">
		<div class="navbar-collapse collapse">
			<div class="container">
				
				<!-- ============================================================= LOGO ============================================================= -->
				
				<a class="navbar-brand" href="index.html"><%= image_tag("logo.png", class: "logo") %></a>
				
				<!-- ============================================================= LOGO : END ============================================================= -->
				
				
				<!-- ============================================================= MAIN NAVIGATION ============================================================= -->
				
				<ul class="nav navbar-nav">
					
					<li class="dropdown">
						<!-- <a href="/">Home</a> -->
					<a href="/">Home</a>
					</li>
					 
					<li class="dropdown">
						<a href="/about">About us</a>
					</li>
					
					<li class="dropdown">
						<a href="/media">Media</a>
					</li>
					
					<li class="dropdown">
						<%= link_to "Bookings" , {:action => "index", :controller => "static_pages", :anchor => "bookings" } %>
					</li>
					
					<li class="dropdown">
						<a href="/auditions">Auditions</a>
					</li>
					
					
				</ul><!-- /.nav -->
				
				<!-- ============================================================= MAIN NAVIGATION : END ============================================================= -->
				
			</div><!-- /.container -->
		</div><!-- /.navbar-collapse -->
	</div><!-- /.yamm -->
</div><!-- /.navbar -->

app/views/layouts/_youtube_video.html.erb
<section id="portfolio-post">
	<div class="container inner-top-xs inner-bottom">
		
		<div class="row">
			<div class="col-sm-12">
				<div class="video-container">
					<iframe src="http://www.youtube.com/embed/<%= path %>" width="1170" height="658" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
				</div>
			</div><!-- /.col -->
		</div><!-- /.row -->
		
	</div><!-- /.container -->
	
</section>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Temptasians of Duke University</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- OnScroll CSS3 Animations for Modern Browsers and IE10+ -->
	<!--[if !IE]> -->
		<%= javascript_include_tag "templates/onscroll.js" %>
	<!-- <![endif]-->
  <!-- Fonts -->
	<link href="http://fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
	<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet">
	<!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
	<!--[if lt IE 9]>
		<script src="assets/js/html5shiv.js"></script>
		<script src="assets/js/respond.min.js"></script>
	<![endif]-->
	<!-- Favicon --> 
	<%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<%= render 'layouts/navigation' %>
</header>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/_youtube.html.erb
<section id="portfolio-post">
	<div class="container inner-top-xs inner-bottom">
		
		<div class="row">
			<div class="col-sm-12">
				<div class="video-container">
					<iframe src="http://www.youtube.com/embed/<%= path %>?autoplay=<%= autoplay %>" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
				</div>
			</div><!-- /.col -->
		</div><!-- /.row -->
		
	</div><!-- /.container -->
	
</section>
	

app/views/static_pages/auditions.html.erb
<main>	
<!-- ============================================================= SECTION – HERO ============================================================= -->

<section id="auditions">
	<div id="owl-main" class="owl-carousel height-lg owl-inner-nav owl-ui-lg">
		
		<div class="item index-page">
			<div class="container">
				
			</div><!-- /.container -->
		</div><!-- /.item -->
	</div><!-- /.owl-carousel -->
</section>
	
	<!-- ============================================================= SECTION – HERO : END ============================================================= -->
<!-- ============================================================= SECTION – Audition ============================================================= -->
<div class="dark-bg auditions-header">
	<h1>Auditions</h1>
</div>
<section class="light-bg">
	<div class="container inner join-us">
		<div class="row">
			<div class="col-md-8 col-sm-9 center-block text-center">
				<header>
					<h1>Want to join us?</h1>
					<p>We are always looking for musical and fun-loving members to join us! Auditions are typically held in the fall, towards the end of the semester. However, if you feel that there is a Temptasian in you that has yet to be discovered, drop us a note at duketemptasians@gmail.com!</p>
				</header>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</section>

<!-- ============================================================= SECTION – Audition : END ============================================================= -->
</main>
<%= javascript_include_tag 'templates/owl-carousel-script.js' %>

app/views/static_pages/from_path.js.erb
$('#portfolio-post').remove();
$("#youtube-video").html("<%= escape_javascript(render partial: 'youtube', locals: { path: @media_path, autoplay: @autoplay } ) %>"); 

app/views/static_pages/index.html.erb
<main>
	<!-- ============================================================= SECTION – HERO ============================================================= -->
	
	<section id="hero">
		<div id="owl-main" class="owl-carousel height-lg owl-inner-nav owl-ui-lg">
			
			<div class="item index-page">
				<div class="container">
					<div class="caption vertical-center text-center">
						<h1 class="fadeInDown-1 light-color">The Temptasians</h1><!-- /.fadeIn -->
						<p class="fadeInDown-2 light-color"><span></span>of Duke University</h1><!-- /.fadeIn -->
					</div><!-- /.caption -->
				</div><!-- /.container -->
			</div><!-- /.item -->
		</div><!-- /.owl-carousel -->
	</section>
	
	<!-- ============================================================= SECTION – HERO : END ============================================================= -->
	
	
	<!-- ============================================================= SECTION – WHO WE ARE ============================================================= -->
	
	<section id="who-we-are">
		<div class="container inner-top inner-bottom-sm">
			
			<div class="row">
				<div class="col-md-8 col-sm-9 center-block text-center">
					<header>
						<h1>Who we are</h1>
						<p>Founded in 2001, The Temptasians are Duke University’s co-ed Asian a cappella group, comprised of talented Asian singers who love to sing. Their repertoire features covers of popular K-Pop and C-Pop songs by singers such as Wheesung (휘성), Taeyang (태양), IU (아이유), Jay Chou (&#21608;&#26480;&#20523;), Wang Leehom (&#29579;&#21147;&#23439;), and JJ Lin. Every February, The Temptasians perform at Duke’s Annual Lunar New Year (LNY) Showcase, which attracts more than a thousand people. The group has also performed at events for various organizations on-campus, such as Duke China Care and Asian Students Association.</p>
					</header>
				</div><!-- /.col -->
			</div><!-- /.row -->
		
		</div><!-- /.container -->
	</section>
	
	<!-- ============================================================= SECTION – WHO WE ARE : END ============================================================= -->
	
	
	<!-- ============================================================= SECTION – LATEST WORKS ============================================================= -->

	<section id="latest-works" class="dark-bg">
		<div class="container inner">
			
			<div class="row description-row">
				<div class="col-md-8 col-sm-9 center-block text-center">
					<header>
						<h1>Check out our latest music video!</h1>
						<p>That's Christmas to Me (Pentatonix Cover)</p>
					</header>
				</div><!-- /.col -->
			</div><!-- /.row -->
			<div class="row">
				<div class="col-sm-12">
					<div class="video-container">
						<iframe src="http://www.youtube.com/embed/xEQvW1wZhJM" width="1170" height="658" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					</div>
				</div><!-- /.col -->
			</div><!-- /.row -->
			
			
		</div><!-- /.container -->
	</section>
	
	<!-- ============================================================= SECTION – LATEST WORKS : END ============================================================= -->
	
	
	<!-- ============================================================= SECTION – GET IN TOUCH ============================================================= -->
	
	<section id="get-in-touch" class="light-bg">
		<div name="bookings" id="bookings" class="container inner">
			<div class="row">
				<div class="col-md-8 col-sm-9 center-block text-center">
					<header>
						<h1>Want to hear us live?</h1>
						<p>We regularly perform at dinners, fundraisers and university functions - just to name a few. To inquire further, please email us at duketemptasians@gmail.com or by clicking on the button below.</p>
					</header>
					<a href="mailto:duketemptasians@gmail.com?subject=Booking Inquiry" class="btn btn-large">Get in touch</a>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container -->
	</section>
	
	<!-- ============================================================= SECTION – GET IN TOUCH : END ============================================================= -->

	

	
			
	
</main>

<!-- ============================================================= MAIN : END ============================================================= -->

  <%= javascript_include_tag 'templates/owl-carousel-script.js' %>

app/views/static_pages/media.html.erb
<!-- ============================================================= MAIN ============================================================= -->
		
<main class="light-bg">
	
	<!-- ============================================================= SECTION – MORE VIDEOS ============================================================= -->
	<section id="more-videos">
		<div class="container inner-top-md">
			<div class="row">
				<div class="col-sm-12">
					<div id="accordion" class="panel-group">
						<div class="panel panel-default">			  
							
							<div class="panel-heading text-center">
								<h4 class="panel-title">
									<a>
										<span>Our Performances</span>
									</a>
								</h4>
							</div><!-- /.panel-heading -->
							
							<div id="content" class="panel-collapse">
								<div class="panel-body">
									<div id="owl-videos" class="owl-carousel owl-item-gap">

										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'xHmjKRIrbkA'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/xHmjKRIrbkA/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'xHmjKRIrbkA'), :remote => true do %>
																DCD Showcase 2015
															<% end %>
														</h4>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->

										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'fSo2glwQ26k'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/fSo2glwQ26k/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'fSo2glwQ26k'), :remote => true do %>
																Korea Night <br>2015
															<% end %>
														</h4>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->
										
										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'xEQvW1wZhJM'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/xEQvW1wZhJM/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'xEQvW1wZhJM'), :remote => true do %>
																That's Christmas to Me
															<% end %>
														</h4>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->
									
										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'bgQ27eInKa0'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/bgQ27eInKa0/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'bgQ27eInKa0'), :remote => true do %>
																Bye Bye Love
															<% end %>
														</h4>
														<p>Alvin Kang & Selina Kim</p>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->
									
										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => '83W3nGRexCM'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/83W3nGRexCM/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => '83W3nGRexCM'), :remote => true do %>
																&#19968;&#30524;&#30636;&#38291;
															<% end %>
														</h4>
														<p>Nancy Zhu & Alex Li</p>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->
									
										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'c8Jwr3TDpog'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/c8Jwr3TDpog/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'c8Jwr3TDpog'), :remote => true do %>
																&#29233;
															<% end %>
														</h4>
														<p>Andrew Ang & Lucy Yin</p>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->

										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'j_TOnC5CMAo'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/j_TOnC5CMAo/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'j_TOnC5CMAo'), :remote => true do %>
																DCD Showcase 2014
															<% end %>
														</h4>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->	

										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => '28y3oxCO7pE'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/28y3oxCO7pE/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => '28y3oxCO7pE'), :remote => true do %>
																&#25105;&#30340;&#27468;&#22768;&#37324;
															<% end %>
														</h4>
														<p>Lucy Yin & Kevin Wu</p>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->	

										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => '0AoDV5T9QGs'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/0AoDV5T9QGs/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => '0AoDV5T9QGs'), :remote => true do %>
																&#22914;&#26524;&#27794;&#26377;&#20320;
															<% end %>
														</h4>
														<p>Alex Li & Ivy Zhou</p>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->	

										<div class="item">
											<figure>
											
												<div class="icon-overlay icn-link">
													<%= link_to fetch_media_path(:youtube_id => 'kGrRYBHkOHo'), {remote: true } do %>
														<%= image_tag("http://img.youtube.com/vi/kGrRYBHkOHo/hqdefault.jpg") %>
													<% end %>
												</div><!-- /.icon-overlay -->
												
												<figcaption class="bordered no-top-border">
													<div class="info">
														<h4>
															<%= link_to fetch_media_path(:youtube_id => 'kGrRYBHkOHo'), :remote => true do %>
																&#52376;&#51020;&#48473;&#44192;&#49845;&#45768;&#45796;
															<% end %>
														</h4>
														<p>JiWon Seo & Alvin Kang</p>
													</div><!-- /.info -->
												</figcaption>
												
											</figure>
										</div><!-- /.item -->	
									</div><!-- /.owl-carousel -->
								</div><!-- /.panel-body -->
							</div><!-- /.content -->
							
						</div><!-- /.panel -->
					</div><!-- /.accordion -->
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container -->
	</section>
	
	<!-- ============================================================= SECTION – MORE VIDEOS : END ============================================================= -->
	
	
	<!-- ============================================================= SECTION – PORTFOLIO POST ============================================================= -->
	<%= render partial: 'youtube', locals: { path: @media_path, autoplay: @autoplay } %>
	<div id="youtube-video"></div>
	<!-- ============================================================= SECTION – PORTFOLIO POST : END ============================================================= -->
	
</main>

<!-- ============================================================= MAIN : END ============================================================= -->

  <%= javascript_include_tag 'templates/owl-carousel-script.js' %>

  <%= javascript_include_tag 'templates/image-hover.js' %>